// Quiz Context
export const INITIALIZE_QUIZ = 'INITALIZE_QUIZ';
export const RESET_QUIZ = 'RESET_QUIZ';
export const PUT_STATE_IN_LOCAL_STORAGE = 'PUT_STATE_IN_LOCAL_STORAGE';
export const RESTORE_STATE_FROM_LOCAL_STORAGE = 'RESTORE_STATE_FROM_LOCAL_STORAGE';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const REQUEST_BOX_SCORES = 'REQUEST_BOX_SCORES';
export const SET_BOX_SCORES = 'SET_BOX_SCORES';